# Generated by Django 5.0.4 on 2024-06-08 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assunto", models.TextField(verbose_name="assunto")),
                ("mensagem", models.TextField(verbose_name="mensagem")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("mecopiar", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="item",
            name="todo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="main.todo",
            ),
        ),
    ]
