# Generated by Django 5.0.4 on 2024-06-08 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_contato_alter_item_todo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contato",
        ),
    ]
